# Generated by Django 4.0.3 on 2022-05-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentuser',
            old_name='assignments',
            new_name='assignment',
        ),
    ]
