# Generated by Django 4.0.3 on 2022-05-02 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_assignments_assignmentuser_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentuser',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_set', to='api.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
